circus/tests: rename async argument of _create_circus() to use_async
In Python 3.7.0, 'async' is now a reserved keyword of the language, so
it cannot be used as an method argument name. When used, it causes the
following byte-compilation failure:

Traceback (most recent call last):
  File "/home/thomas/projets/buildroot/output/host/lib/python3.7/py_compile.py", line 136, in compile
    _optimize=optimize)
  File "<frozen importlib._bootstrap_external>", line 763, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "usr/lib/python3.7/site-packages/circus/tests/support.py", line 210
    debug=debug, async=True, **kw)
                     ^
SyntaxError: invalid syntax

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>